server:
  port: 8888
spring:
  application:
    name: oj-sandbox
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.130:8848
        # 使用与网关相同的命名空间
        namespace: bdd24507-ab90-4409-941a-5d6eb60739cf
        # 基础设施服务组
        group: INFRASTRUCTURE
        # 标记为内部服务的元数据
        metadata:
          internal: true
          service-type: sandbox
          version: v1.0
        # 健康检查配置
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        # 服务实例权重
        weight: 1.0
        # 集群名称
        cluster-name: default
        # 是否为临时实例
        ephemeral: true

# 健康检查端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    root: INFO
    com.alibaba.nacos.client.config.impl: WARN
    fun.timu.oj.shandbox: DEBUG